### ISSUE TITLE
[OS X] Issues initializing

### ISSUE THREAD

**Issue by mr-feek** [AdrienPoupa/laradose#2]
Hiya 👋 

Neat package! I'm on os x, and am going to document some issues with installation.

`./laradose.sh --install`
- [ ] all project files get mutated
> diff --git a/.eslintrc.json b/.eslintrc.json
old mode 100644
new mode 100755

- [ ] Sed issues ( I assume these are because os x ships with a different sed than linux)

> sed: 1: "package.json": extra characters at the end of p command
Type the container number (again to uncheck, ENTER when done):
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
sed: 1: "./.env": invalid command code .
Linux User ID for file permissions (current user: 501): [1000] 501
sed: 1: "./.env": invalid command code .

**Comment by AdrienPoupa** [comment]
Hello, thank you!

Yes indeed I could not test it on
OS X, thanks for doing it!

I'd assume the Bash environment differs from Linux.

I will check if I can find a different way and let you know

**Comment by mr-feek** [comment]
@AdrienPoupa are [these commands](https://github.com/AdrienPoupa/laradose/blob/master/laradose.sh#L181-L183) really necessary? Doesn't laravel have the correct permissions setup by default?

**Comment by mr-feek** [comment]
Something like https://stackoverflow.com/a/38595160/3781678 may work for the sed replacement!
